export const FORECAST_LOCATION_REQUEST = 'FORECAST_LOCATION_REQUEST'
export const FORECAST_LOCATION_SUCCESS = 'FORECAST_LOCATION_SUCCESS'
export const FORECAST_LOCATION_FAIL = 'FORECAST_LOCATION_FAIL'

export const FORECAST_DETAILS_REQUEST = 'FORECAST_DETAILS_REQUEST'
export const FORECAST_DETAILS_SUCCESS = 'FORECAST_DETAILS_SUCCESS'
export const FORECAST_DETAILS_FAIL = 'FORECAST_DETAILS_FAIL'

export const FORECAST_DAILY_REQUEST = 'FORECAST_DAILY_REQUEST'
export const FORECAST_DAILY_SUCCESS = 'FORECAST_DAILY_SUCCESS'
export const FORECAST_DAILY_FAIL = 'FORECAST_DAILY_FAIL'
